<script lang="ts">
	import PageSection from '$lib/components/PageSection.svelte';
	import { ArrowLeft } from 'lucide-svelte';
</script>

<svelte:head>
	<title>Demand Documentation — Energy Toolkit</title>
</svelte:head>

<PageSection>
	<a href="/docs" class="mb-6 inline-flex items-center gap-1 text-sm text-brand-teal hover:text-brand-med-teal transition-colors">
		<ArrowLeft size={14} /> Back to Docs
	</a>

	<h1 class="mb-4 text-4xl font-bold text-brand-navy">Demand Documentation</h1>
	<p class="mb-8 max-w-2xl text-text-dark/70">
		Technical reference for the Demand tool.
		Source: <a href="https://github.com/aidotse/behovskartan" target="_blank" rel="noopener noreferrer" class="text-link hover:underline">github.com/aidotse/behovskartan</a>
	</p>
</PageSection>

<!-- Data pipeline -->
<PageSection bg="bg-white">
	<div class="mx-auto max-w-4xl prose prose-lg prose-headings:font-display prose-headings:text-brand-navy prose-a:text-link">
		<h2>Data Pipeline</h2>
		<ol>
			<li><strong>Data Generation</strong> — Generator (Python) creates Parquet files in <code>/data/</code></li>
			<li><strong>Static Endpoints</strong> — <code>generate-api.js</code> builds JSON files in <code>/data/</code></li>
			<li><strong>API Server</strong> — Express + OpenAPI Backend serves validated endpoints + DuckDB queries</li>
			<li><strong>Frontend Loading</strong> — <code>+page.ts</code> fetches initial data and passes props to components</li>
			<li><strong>Component Data</strong> — Hybrid pattern: components accept props OR fetch their own data</li>
		</ol>

		<h2>API Endpoints</h2>

		<h3>Static Endpoints</h3>
		<p>Pre-built JSON files served directly. Regenerated by <code>node generate-api.js --defaults</code>.</p>
		<table>
			<thead>
				<tr><th>Endpoint</th><th>Description</th></tr>
			</thead>
			<tbody>
				<tr><td><code>GET /globals</code></td><td>Min/max bounds for different aggregation levels</td></tr>
				<tr><td><code>GET /parameters</code></td><td>Available years, geographies, segments, resolutions</td></tr>
				<tr><td><code>GET /scenarios</code></td><td>Scenario definitions with growth rates and parameter combinations</td></tr>
				<tr><td><code>GET /geographies</code></td><td>Geography metadata and GeoJSON</td></tr>
				<tr><td><code>GET /config</code></td><td>General configuration</td></tr>
			</tbody>
		</table>

		<h3>Dynamic Endpoints</h3>
		<p><code>GET /demand</code> — Time series data powered by DuckDB queries on Parquet files.</p>
		<ul>
			<li><strong>Resolutions:</strong> <code>1h</code>, <code>1d</code>, <code>1w</code>, <code>1M</code>, <code>1Y</code></li>
			<li><strong>Aggregations:</strong> <code>sum</code>, <code>mean</code>, <code>max</code></li>
			<li><strong>Filters:</strong> scenario, geography, segment, time range</li>
			<li>Use <code>geography='total'</code> and <code>segment='total'</code> for server-side aggregation</li>
		</ul>

		<h3>Response Format</h3>
		<p>Time series data returns an array of records:</p>
		<pre><code>{`{ "period": "2025-01-01T00:00:00Z", "value": 123.45, "geography": "SE01", "segment": "housing" }`}</code></pre>

		<h2>Data Structure</h2>
		<h3>Parquet File Organization</h3>
<pre><code>{`/data/
├── base/
│   └── {scenario_id}/
│       └── data.parquet            # Base scenario data
├── scenarios/
│   └── {param1}={val1}/
│       └── {param2}={val2}/
│           └── data.parquet        # Parametric variations
├── aggregated/
│   ├── geography_yearly.parquet    # For maps
│   ├── segment_yearly.parquet      # For sector charts
│   ├── national_yearly.parquet     # For time series
│   └── scenario_metadata.parquet   # Parameter combinations
└── [static JSON endpoints]`}</code></pre>

		<h3>Key Patterns</h3>
		<ul>
			<li><strong>Base vs Scenarios</strong> — Base scenarios have NULL parameter columns; parametric scenarios have values</li>
			<li><strong>UNION Queries</strong> — DuckDB combines base and parametric data with schema normalization</li>
			<li><strong>Pre-aggregation</strong> — Generator creates aggregated tables for 50-100x speedup on common queries</li>
			<li><strong>Predicate pushdown</strong> — DuckDB pushes filters into Parquet scanning for fast queries</li>
		</ul>

		<h2>Static Endpoint Generation</h2>
		<p>
			<code>generate-api.js</code> is the master script that orchestrates all static endpoint generation.
			It calls <code>generate-endpoints.js</code> which runs individual endpoint functions:
		</p>
		<table>
			<thead>
				<tr><th>Output File</th><th>Source Function</th><th>Inputs</th></tr>
			</thead>
			<tbody>
				<tr><td><code>parameters.json</code></td><td><code>generateParameters()</code></td><td><code>parameters.yaml</code> + <code>openapi.yaml</code></td></tr>
				<tr><td><code>geographies.json</code></td><td><code>generateGeographies()</code></td><td><code>config.yaml</code></td></tr>
				<tr><td><code>scenarios.json</code></td><td><code>generateScenarios()</code></td><td><code>config.yaml</code></td></tr>
				<tr><td><code>aggregations.json</code></td><td><code>generateAggregations()</code></td><td><code>config.yaml</code></td></tr>
				<tr><td><code>config.json</code></td><td><code>generateConfig()</code></td><td><code>config.yaml</code></td></tr>
				<tr><td><code>globals.json</code></td><td><code>generateGlobalsFile()</code></td><td>Parquet files via DuckDB</td></tr>
			</tbody>
		</table>

		<h2>Explorer Architecture</h2>
		<p>
			The Explorer is a modular visual framework designed for easy customization. Components
			can be added, removed, or replaced independently.
		</p>

		<h3>Technology Stack</h3>
		<ul>
			<li><strong>Framework:</strong> SvelteKit with Svelte 5 runes (<code>$state</code>, <code>$derived</code>, <code>$effect</code>)</li>
			<li><strong>Styling:</strong> Tailwind CSS 3.4+ with container queries, typography, and forms plugins</li>
			<li><strong>Charts:</strong> LayerChart (SVG-based) with D3 utilities for scales and arrays</li>
			<li><strong>Maps:</strong> Mapbox GL JS for choropleth visualization</li>
			<li><strong>Content:</strong> MDsveX for Markdown with embedded Svelte components</li>
			<li><strong>i18n:</strong> Paraglide for type-safe internationalization</li>
		</ul>

		<h3>Component Patterns</h3>
		<ul>
			<li><strong>Hybrid data loading</strong> — Components accept <code>data</code> as props; if null/empty, they fetch their own data</li>
			<li><strong>Standardized interfaces</strong> — <code>BaseChartProps</code>, <code>TimeSeriesChartProps</code>, <code>GeographicChartProps</code></li>
			<li><strong>Container queries</strong> — Components respond to container width, not viewport</li>
			<li><strong>Shared UI</strong> — <code>LoadingSkeleton</code>, <code>ErrorState</code>, <code>EmptyState</code> with loading/error/empty variants</li>
		</ul>

		<h3>Content System</h3>
		<p>
			Markdown files in <code>/src/content/{'{locale}'}/</code> with YAML frontmatter.
			A custom directive preprocessor transforms <code>:::Component{'{props}'}</code> syntax
			into Svelte component tags, allowing domain experts to embed interactive visualizations
			in narrative content.
		</p>

		<h3>Chart Export</h3>
		<ul>
			<li><strong>SVG:</strong> Extracts SVG from LayerChart components — working</li>
			<li><strong>CSV:</strong> Chart data with metadata headers — working</li>
			<li><strong>JSON:</strong> Full data with metadata object — working</li>
			<li><strong>PNG:</strong> Canvas-based rendering — partial (style preservation issues)</li>
		</ul>

		<h2>Deployment</h2>
		<p>
			Deploys to AWS using GitHub Actions with OIDC authentication (no stored AWS keys).
		</p>
		<table>
			<thead>
				<tr><th>Component</th><th>Service</th><th>Cost</th></tr>
			</thead>
			<tbody>
				<tr><td>Frontend</td><td>S3 + CloudFront</td><td>~$1/month</td></tr>
				<tr><td>API</td><td>AWS App Runner (Docker)</td><td>~$25/month</td></tr>
			</tbody>
		</table>

		<h3>Pipeline</h3>
		<p>Triggered by push to <code>production</code> branch or manual dispatch:</p>
		<ol>
			<li><strong>build-api</strong> — Build Docker image, push to ECR</li>
			<li><strong>deploy-api</strong> — Update App Runner, wait for health check</li>
			<li><strong>deploy-explorer</strong> — Build static site, sync to S3, invalidate CloudFront</li>
		</ol>

		<h3>Branch Strategy</h3>
		<table>
			<thead><tr><th>Branch</th><th>Purpose</th></tr></thead>
			<tbody>
				<tr><td><code>main</code></td><td>Development integration</td></tr>
				<tr><td><code>feature/*</code></td><td>Feature branches, merged via PR</td></tr>
				<tr><td><code>production</code></td><td>Deployment trigger</td></tr>
			</tbody>
		</table>

		<h2>Development Practices</h2>

		<h3>Coding Standards</h3>
		<ul>
			<li>Svelte 5 runes only — no Svelte 4 syntax</li>
			<li>TypeScript throughout with strict mode</li>
			<li>Python follows PEP 8</li>
			<li>Conventional commits: <code>type(scope): description</code></li>
		</ul>

		<h3>Testing</h3>
		<ul>
			<li><strong>API:</strong> <code>cd api &amp;&amp; npm test</code> — query builders, cache, endpoints</li>
			<li><strong>Explorer:</strong> <code>cd explorer &amp;&amp; npm test</code> — components, utilities, content loading</li>
			<li><strong>E2E:</strong> <code>cd explorer &amp;&amp; npm run test:e2e</code> — Playwright browser tests</li>
			<li><strong>Generator:</strong> <code>cd generator &amp;&amp; pytest</code> — data generation validation</li>
		</ul>

		<h3>Common Issues</h3>
		<ul>
			<li><strong>API floods</strong> — Components re-fetching on every parameter change. Use <code>$effect</code> with debouncing.</li>
			<li><strong>Map bounds</strong> — GeoJSON must be loaded before setting map bounds. Check data availability in <code>$effect</code>.</li>
			<li><strong>MDsveX smart quotes</strong> — Don't use single-quoted strings in inline template expressions in <code>.md</code> files. Define data arrays in <code>&lt;script&gt;</code> blocks.</li>
		</ul>
	</div>
</PageSection>
